# Generated by Django 3.2.9 on 2024-07-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='hosted_by',
            new_name='hostedBy',
        ),
        migrations.RenameField(
            model_name='contestresult',
            old_name='contest_name',
            new_name='contestName',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='correct_option',
            new_name='correctOption',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='submition_time',
            new_name='submitionTime',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_answer',
            new_name='userAnswer',
        ),
        migrations.AlterUniqueTogether(
            name='contestresult',
            unique_together={('contestName', 'rank')},
        ),
    ]
