# Generated by Django 3.2.9 on 2024-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20240714_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
