# Generated by Django 3.0.5 on 2020-04-28 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('p1class', models.CharField(max_length=10)),
                ('p2class', models.CharField(max_length=10)),
                ('monitor_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
