# Generated by Django 3.0.5 on 2020-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_no', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('pgmInput', models.TextField(default='')),
                ('expOutput', models.TextField(default='')),
            ],
        ),
    ]
