# Generated by Django 3.0.3 on 2020-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField()),
                ('no_alloted_tasks', models.IntegerField()),
                ('status', models.CharField(choices=[('Running', 'Server is Active'), ('Stopped', 'Server is not running')], default='Stopped', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tId', models.AutoField(primary_key=True, serialize=False)),
                ('submission_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Running', 'Task is running'), ('Submitted', 'Task is registered'), ('Completed', 'Task is complete')], default='Submitted', max_length=20)),
                ('task_type', models.CharField(choices=[('Execute Code', 'Task for running program'), ('Evaluate Result', 'Task for scoring the result')], max_length=20)),
                ('info', models.TextField()),
            ],
        ),
    ]
