# Generated by Django 3.0.3 on 2020-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='hosted_by',
            field=models.CharField(default='', max_length=150),
        ),
    ]
