# Generated by Django 3.0.5 on 2020-05-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50, unique=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('cqId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=250)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.MCQ_Questions')),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testCaseType', models.CharField(choices=[('Hidden', 'Output and Input will be hidden from user'), ('Visiable', 'Output and Input will be shown to user')], max_length=30)),
                ('pgmInput', models.TextField(default='')),
                ('OutputType', models.CharField(choices=[('Static', 'Program output will be same for the given input'), ('Dynamic', 'Program ouput will be different for the given input')], max_length=30)),
                ('pgmOutputOrEvalCode', models.TextField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.CodingQuestions')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='codingquestions',
            name='cqId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestQuestions'),
        ),
        migrations.AddConstraint(
            model_name='contestquestions',
            constraint=models.UniqueConstraint(fields=('cId', 'qno'), name='name of constraint'),
        ),
    ]
