# Generated by Django 3.0.3 on 2020-11-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20201109_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='submition_time',
            field=models.DateTimeField(null=True),
        ),
    ]
