# Generated by Django 3.0.2 on 2020-05-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_auto_20200501_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='correct_option',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.IntegerField()),
                ('user_answer', models.TextField()),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('rank', models.IntegerField()),
                ('submition_time', models.TimeField()),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
