# Generated by Django 3.0.2 on 2020-05-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20200501_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(default=9999999),
        ),
    ]
