# Generated by Django 3.0.3 on 2020-11-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20201116_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='submition_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
