# Generated by Django 3.0.5 on 2020-05-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20200501_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingQuestions',
            new_name='CodingQuestion',
        ),
        migrations.RenameModel(
            old_name='ContestQuestions',
            new_name='ContestQuestion',
        ),
        migrations.RenameModel(
            old_name='MCQ_Questions',
            new_name='McqQuestion',
        ),
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pname',
        ),
    ]
