# Generated by Django 3.0.5 on 2020-05-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20200501_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='cId',
            new_name='contest',
        ),
    ]
