# Generated by Django 3.0.5 on 2020-05-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20200502_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='cqId',
        ),
        migrations.RemoveField(
            model_name='mcqquestion',
            name='cqId',
        ),
    ]
