# Generated by Django 3.0.5 on 2020-05-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20200502_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestquestion',
            name='codingQues',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.CodingQuestion'),
        ),
        migrations.AddField(
            model_name='contestquestion',
            name='mcqQues',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.McqQuestion'),
        ),
    ]
