# Generated by Django 3.0.5 on 2020-05-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20200517_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='question',
        ),
        migrations.DeleteModel(
            name='CodingQuestion',
        ),
        migrations.DeleteModel(
            name='McqQuestion',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
