# Generated by Django 3.0.5 on 2020-05-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20200517_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('cq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('cq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testCaseType', models.CharField(choices=[('Hidden', 'Output and Input will be hidden from user'), ('Visible', 'Output and Input will be shown to user')], max_length=30)),
                ('pgmInput', models.TextField(default='')),
                ('OutputType', models.CharField(choices=[('Static', 'Program output will be same for the given input'), ('Dynamic', 'Program ouput will be different for the given input')], max_length=30)),
                ('pgmOutputOrEvalCode', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.CodingQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=250)),
                ('correct_option', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.McqQuestion')),
            ],
        ),
    ]
