# Generated by Django 3.0.5 on 2020-05-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_codingquestion_mcqquestion_option_testcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Response',
        ),
    ]
