# Generated by Django 3.0.5 on 2020-05-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_delete_user_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCodeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('language', models.CharField(choices=[('Python', 'Python pgm'), ('C++', 'C++ pgm'), ('C', 'C Program')], max_length=50)),
                ('answer', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('language', models.CharField(choices=[('Python', 'Python pgm'), ('C++', 'C++ pgm'), ('C', 'C Program')], max_length=50)),
                ('user_answer', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tempcodecache',
            constraint=models.UniqueConstraint(fields=('participant', 'qno', 'language'), name='Unique answer cache for participant'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('participant', 'qno'), name='Unique qno for participant'),
        ),
    ]
