# Generated by Django 3.0.5 on 2020-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20200518_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='userId',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'contest'), name='Unique user for contest'),
        ),
    ]
