# Generated by Django 3.0.5 on 2020-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_auto_20200518_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='submition_time',
            field=models.TimeField(null=True),
        ),
    ]
