# Generated by Django 3.0.3 on 2020-11-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20200518_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
