# Generated by Django 3.1.3 on 2020-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_contest_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
